export default {
  login: "IonVajda",
  id: 56801202,
  node_id: "MDQ6VXNlcjU2ODAxMjAy",
  avatar_url: "https://avatars0.githubusercontent.com/u/56801202?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/IonVajda",
  html_url: "https://github.com/IonVajda",
  followers_url: "https://api.github.com/users/IonVajda/followers",
  following_url: "https://api.github.com/users/IonVajda/following{/other_user}",
  gists_url: "https://api.github.com/users/IonVajda/gists{/gist_id}",
  starred_url: "https://api.github.com/users/IonVajda/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/IonVajda/subscriptions",
  organizations_url: "https://api.github.com/users/IonVajda/orgs",
  repos_url: "https://api.github.com/users/IonVajda/repos",
  events_url: "https://api.github.com/users/IonVajda/events{/privacy}",
  received_events_url: "https://api.github.com/users/IonVajda/received_events",
  type: "User",
  site_admin: false,
  name: "Ion Vajda",
  company: null,
  blog: "",
  location: "Milan",
  email: null,
  hireable: true,
  bio: "Junior Front End Developer",
  twitter_username: "Ionut24V",
  public_repos: 14,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: "2019-10-20T18:40:01Z",
  updated_at: "2020-08-15T15:03:34Z",
};
